/**
 * ACES Listener API
 * API Specification for ACES Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AcesListenerApi) {
      root.AcesListenerApi = {};
    }
    root.AcesListenerApi.Health = factory(root.AcesListenerApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Health model module.
   * @module model/Health
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>Health</code>.
   * @alias module:model/Health
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Health</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Health} obj Optional instance to populate.
   * @return {module:model/Health} The populated <code>Health</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Health.StatusEnum} status
   */
  exports.prototype['status'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "up"
     * @const
     */
    "up": "up",
    /**
     * value: "down"
     * @const
     */
    "down": "down"  };


  return exports;
}));


