/**
 * Aces Encoded Listener API
 * API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Health model module.
* @module model/Health
* @version 0.1.0
*/
export default class Health {
    /**
    * Constructs a new <code>Health</code>.
    * @alias module:model/Health
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Health</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Health} obj Optional instance to populate.
    * @return {module:model/Health} The populated <code>Health</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Health();

            
            
            

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Health.StatusEnum} status
    */
    status = undefined;






    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
    
        /**
         * value: "up"
         * @const
         */
        "up": "up",
    
        /**
         * value: "down"
         * @const
         */
        "down": "down"    
    };



}


