/**
 * Aces Encoded Listener API
 * API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NotFoundError model module.
* @module model/NotFoundError
* @version 0.1.0
*/
export default class NotFoundError {
    /**
    * Constructs a new <code>NotFoundError</code>.
    * @alias module:model/NotFoundError
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>NotFoundError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NotFoundError} obj Optional instance to populate.
    * @return {module:model/NotFoundError} The populated <code>NotFoundError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotFoundError();

            
            
            

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * @member {String} message
    */
    message = undefined;








}


