/**
 * Aces Encoded Listener API
 * API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SubscriptionRequest model module.
* @module model/SubscriptionRequest
* @version 0.1.0
*/
export default class SubscriptionRequest {
    /**
    * Constructs a new <code>SubscriptionRequest</code>.
    * @alias module:model/SubscriptionRequest
    * @class
    * @param host {String} Target host implementing Encoded Listener Subscriber API interface.
    * @param minConfirmations {Number} Confirmations required before event is sent to subscribers.
    */

    constructor(host, minConfirmations) {
        

        
        

        this['host'] = host;this['min_confirmations'] = minConfirmations;

        
    }

    /**
    * Constructs a <code>SubscriptionRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SubscriptionRequest} obj Optional instance to populate.
    * @return {module:model/SubscriptionRequest} The populated <code>SubscriptionRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionRequest();

            
            
            

            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('min_confirmations')) {
                obj['min_confirmations'] = ApiClient.convertToType(data['min_confirmations'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Target host implementing Encoded Listener Subscriber API interface.
    * @member {String} host
    */
    host = undefined;
    /**
    * Confirmations required before event is sent to subscribers.
    * @member {Number} min_confirmations
    */
    min_confirmations = undefined;








}


