/**
 * ACES Listener API
 * API Specification for ACES Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AcesListenerApi) {
      root.AcesListenerApi = {};
    }
    root.AcesListenerApi.SubscriptionEvent = factory(root.AcesListenerApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SubscriptionEvent model module.
   * @module model/SubscriptionEvent
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>SubscriptionEvent</code>.
   * @alias module:model/SubscriptionEvent
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>SubscriptionEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionEvent} obj Optional instance to populate.
   * @return {module:model/SubscriptionEvent} The populated <code>SubscriptionEvent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('tries')) {
        obj['tries'] = ApiClient.convertToType(data['tries'], 'Number');
      }
      if (data.hasOwnProperty('transactionId')) {
        obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], 'String');
      }
    }
    return obj;
  }

  /**
   * Subscription Event identifier
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Date the Subscription Event was created.
   * @member {Date} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {module:model/SubscriptionEvent.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Number} tries
   */
  exports.prototype['tries'] = undefined;
  /**
   * Transaction id blockchain event.
   * @member {String} transactionId
   */
  exports.prototype['transactionId'] = undefined;
  /**
   * Event data encoded as a Json string.
   * @member {String} data
   */
  exports.prototype['data'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "new"
     * @const
     */
    "new": "new",
    /**
     * value: "delivered"
     * @const
     */
    "delivered": "delivered",
    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"  };


  return exports;
}));


