/**
 * Aces Encoded Listener API
 * API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SubscriptionEvent model module.
* @module model/SubscriptionEvent
* @version 0.1.0
*/
export default class SubscriptionEvent {
    /**
    * Constructs a new <code>SubscriptionEvent</code>.
    * @alias module:model/SubscriptionEvent
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SubscriptionEvent</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SubscriptionEvent} obj Optional instance to populate.
    * @return {module:model/SubscriptionEvent} The populated <code>SubscriptionEvent</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionEvent();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('tries')) {
                obj['tries'] = ApiClient.convertToType(data['tries'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
        }
        return obj;
    }

    /**
    * Subscription Event identifier
    * @member {String} id
    */
    id = undefined;
    /**
    * Date the Subscription Event was created.
    * @member {Date} created_at
    */
    created_at = undefined;
    /**
    * @member {module:model/SubscriptionEvent.StatusEnum} status
    */
    status = undefined;
    /**
    * @member {Number} tries
    */
    tries = undefined;
    /**
    * Event data encoded as a Json string.
    * @member {String} data
    */
    data = undefined;






    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
    
        /**
         * value: "new"
         * @const
         */
        "new": "new",
    
        /**
         * value: "delivered"
         * @const
         */
        "delivered": "delivered",
    
        /**
         * value: "failed"
         * @const
         */
        "failed": "failed"    
    };



}


