/**
 * ACES Listener API
 * API Specification for ACES Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import FieldError from './FieldError';





/**
* The ValidationError model module.
* @module model/ValidationError
* @version 1.0.0
*/
export default class ValidationError {
    /**
    * Constructs a new <code>ValidationError</code>.
    * @alias module:model/ValidationError
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ValidationError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ValidationError} obj Optional instance to populate.
    * @return {module:model/ValidationError} The populated <code>ValidationError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationError();

            
            
            

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('fieldErrors')) {
                obj['fieldErrors'] = ApiClient.convertToType(data['fieldErrors'], [FieldError]);
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {Array.<module:model/FieldError>} fieldErrors
    */
    fieldErrors = undefined;








}


