/* 
 * Aces Encoded Listener API
 *
 * API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArkAces.EncodedListenerClient.Api;
using ArkAces.EncodedListenerClient.Model;
using ArkAces.EncodedListenerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArkAces.EncodedListenerClient.Test
{
    /// <summary>
    ///  Class for testing FieldError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FieldErrorTests
    {
        // TODO uncomment below to declare an instance variable for FieldError
        //private FieldError instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FieldError
            //instance = new FieldError();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FieldError
        /// </summary>
        [Test]
        public void FieldErrorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldError
            //Assert.IsInstanceOfType<FieldError> (instance, "variable 'instance' is a FieldError");
        }


        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Test]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
