/* 
 * Aces Encoded Listener API
 *
 * API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArkAces.EncodedListenerClient.Api;
using ArkAces.EncodedListenerClient.Model;
using ArkAces.EncodedListenerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArkAces.EncodedListenerClient.Test
{
    /// <summary>
    ///  Class for testing SubscriptionUnsubscribe
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubscriptionUnsubscribeTests
    {
        // TODO uncomment below to declare an instance variable for SubscriptionUnsubscribe
        //private SubscriptionUnsubscribe instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubscriptionUnsubscribe
            //instance = new SubscriptionUnsubscribe();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubscriptionUnsubscribe
        /// </summary>
        [Test]
        public void SubscriptionUnsubscribeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubscriptionUnsubscribe
            //Assert.IsInstanceOfType<SubscriptionUnsubscribe> (instance, "variable 'instance' is a SubscriptionUnsubscribe");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
