# coding: utf-8

"""
    ACES Listener API

    API Specification for ACES Listeners that read data on a blockchain and forward transaction events to registered subscribers.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import com.arkaces.aces_listener_api
from com.arkaces.aces_listener_api.api.aces_listener_api import AcesListenerApi  # noqa: E501
from com.arkaces.aces_listener_api.rest import ApiException


class TestAcesListenerApi(unittest.TestCase):
    """AcesListenerApi unit test stubs"""

    def setUp(self):
        self.api = com.arkaces.aces_listener_api.api.aces_listener_api.AcesListenerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_get(self):
        """Test case for status_get

        Get Health of node.  # noqa: E501
        """
        pass

    def test_subscriptions_id_events_get(self):
        """Test case for subscriptions_id_events_get

        List Subscription Events  # noqa: E501
        """
        pass

    def test_subscriptions_id_get(self):
        """Test case for subscriptions_id_get

        Gets Subscription  # noqa: E501
        """
        pass

    def test_subscriptions_id_resubscribes_post(self):
        """Test case for subscriptions_id_resubscribes_post

        Create a Resubscribe.  # noqa: E501
        """
        pass

    def test_subscriptions_id_unsubscribes_post(self):
        """Test case for subscriptions_id_unsubscribes_post

        Create an Unsubscription.  # noqa: E501
        """
        pass

    def test_subscriptions_post(self):
        """Test case for subscriptions_post

        Registers a subscriber node to receive blockchain events.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
