# coding: utf-8

"""
    Aces Encoded Listener API

    API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import io.arkaces.encoded_listener_client
from io.arkaces.encoded_listener_client.rest import ApiException
from io.arkaces.encoded_listener_client.models.inline_response_200 import InlineResponse200


class TestInlineResponse200(unittest.TestCase):
    """ InlineResponse200 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200(self):
        """
        Test InlineResponse200
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = io.arkaces.encoded_listener_client.models.inline_response_200.InlineResponse200()
        pass


if __name__ == '__main__':
    unittest.main()
