/*
 * Aces Encoded Listener API
 *
 * API Specification for Encoded Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/encoded-listener-client

type InlineResponse200 struct {

	PageSize int32 `json:"page_size,omitempty"`

	Page int32 `json:"page,omitempty"`

	Continuation string `json:"continuation,omitempty"`

	Items []SubscriptionEvent `json:"items,omitempty"`
}
