/*
 * ACES Listener API
 *
 * API Specification for ACES Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package arkaces/encoded-listener-client

import (
	"time"
)

type SubscriptionUnsubscribe struct {

	// Unsubscription identifier
	Id string `json:"id,omitempty"`

	// Date the Unsubscription was created.
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
