/* 
 * ACES Listener API
 *
 * API Specification for ACES Listeners that read data on a blockchain and forward transaction events to registered subscribers. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArkAces.EncodedListenerClient.Client.SwaggerDateConverter;

namespace ArkAces.EncodedListenerClient.Model
{
    /// <summary>
    /// SubscriptionRequest
    /// </summary>
    [DataContract]
    public partial class SubscriptionRequest :  IEquatable<SubscriptionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubscriptionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionRequest" /> class.
        /// </summary>
        /// <param name="CallbackUrl">Target target URL to POST Encoded Listener events to. (required).</param>
        /// <param name="MinConfirmations">Confirmations required before event is sent to subscriber. (required).</param>
        public SubscriptionRequest(string CallbackUrl = default(string), int? MinConfirmations = default(int?))
        {
            // to ensure "CallbackUrl" is required (not null)
            if (CallbackUrl == null)
            {
                throw new InvalidDataException("CallbackUrl is a required property for SubscriptionRequest and cannot be null");
            }
            else
            {
                this.CallbackUrl = CallbackUrl;
            }
            // to ensure "MinConfirmations" is required (not null)
            if (MinConfirmations == null)
            {
                throw new InvalidDataException("MinConfirmations is a required property for SubscriptionRequest and cannot be null");
            }
            else
            {
                this.MinConfirmations = MinConfirmations;
            }
        }
        
        /// <summary>
        /// Target target URL to POST Encoded Listener events to.
        /// </summary>
        /// <value>Target target URL to POST Encoded Listener events to.</value>
        [DataMember(Name="callbackUrl", EmitDefaultValue=false)]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// Confirmations required before event is sent to subscriber.
        /// </summary>
        /// <value>Confirmations required before event is sent to subscriber.</value>
        [DataMember(Name="minConfirmations", EmitDefaultValue=false)]
        public int? MinConfirmations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscriptionRequest {\n");
            sb.Append("  CallbackUrl: ").Append(CallbackUrl).Append("\n");
            sb.Append("  MinConfirmations: ").Append(MinConfirmations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubscriptionRequest);
        }

        /// <summary>
        /// Returns true if SubscriptionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SubscriptionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscriptionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CallbackUrl == input.CallbackUrl ||
                    (this.CallbackUrl != null &&
                    this.CallbackUrl.Equals(input.CallbackUrl))
                ) && 
                (
                    this.MinConfirmations == input.MinConfirmations ||
                    (this.MinConfirmations != null &&
                    this.MinConfirmations.Equals(input.MinConfirmations))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CallbackUrl != null)
                    hashCode = hashCode * 59 + this.CallbackUrl.GetHashCode();
                if (this.MinConfirmations != null)
                    hashCode = hashCode * 59 + this.MinConfirmations.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
